/**
 * import-data-from-supabase.ts
 * ----------------------------
 * ONE-TIME migration script: copies all rows of the 11 app tables from
 * Supabase (via the PostgREST API, using the service key — no direct DB
 * password needed) into the new Postgres (DATABASE_URL).
 *
 * - Preserves original id values (OVERRIDING SYSTEM VALUE) and resets
 *   the identity sequences afterwards.
 * - Refuses to touch any target table that already contains rows, so it
 *   can be re-run safely after a partial failure.
 *
 * Required env vars:
 *   DATABASE_URL          — the NEW Postgres connection string
 *   SUPABASE_URL          — the OLD Supabase project URL
 *   SUPABASE_SECRET_KEY   — the OLD Supabase service-role/secret key
 *
 * Usage:
 *   npx tsx --env-file=.env scripts/import-data-from-supabase.ts
 */

import { sql } from "drizzle-orm";
import type { PgTable } from "drizzle-orm/pg-core";
import { getDb, schema } from "./db";

const PAGE_SIZE = 1000;

/* eslint-disable @typescript-eslint/no-explicit-any */
type Row = Record<string, any>;

const date = (v: string | null | undefined): Date | null => (v ? new Date(v) : null);

interface TableSpec {
    /** Table name in Supabase (snake_case) */
    name: string;
    table: PgTable;
    /** Column used for stable pagination ordering */
    orderBy: string;
    /** Whether the table has a GENERATED ALWAYS identity id */
    identity: boolean;
    /** Map a PostgREST JSON row to drizzle insert values */
    map: (r: Row) => Row;
}

/* Ordered so FK targets load before referencing tables
   (job_openings before job_applications). */
const TABLES: TableSpec[] = [
    {
        name: "app_config",
        table: schema.appConfig,
        orderBy: "key",
        identity: false,
        map: (r) => ({
            key: r.key,
            value: r.value,
            description: r.description,
            updatedAt: date(r.updated_at) ?? new Date(),
        }),
    },
    {
        name: "admin_users",
        table: schema.adminUsers,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            email: r.email,
            passwordHash: r.password_hash,
            name: r.name,
            createdAt: date(r.created_at) ?? new Date(),
            lastLoginAt: date(r.last_login_at),
        }),
    },
    {
        name: "api_tokens",
        table: schema.apiTokens,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            tokenHash: r.token_hash,
            name: r.name,
            createdAt: date(r.created_at) ?? new Date(),
            expiresAt: date(r.expires_at),
            revokedAt: date(r.revoked_at),
            lastUsedAt: date(r.last_used_at),
        }),
    },
    {
        name: "contacts",
        table: schema.contacts,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            name: r.name,
            email: r.email,
            company: r.company,
            phone: r.phone,
            message: r.message,
            serviceType: r.service_type,
            budget: r.budget,
            createdAt: date(r.created_at) ?? new Date(),
        }),
    },
    {
        name: "subscribers",
        table: schema.subscribers,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            email: r.email,
            createdAt: date(r.created_at) ?? new Date(),
        }),
    },
    {
        name: "job_openings",
        table: schema.jobOpenings,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            title: r.title,
            department: r.department,
            location: r.location,
            type: r.type,
            status: r.status,
            description: r.description,
            applyUrl: r.apply_url,
            sortOrder: r.sort_order,
            createdAt: date(r.created_at) ?? new Date(),
            updatedAt: date(r.updated_at) ?? new Date(),
        }),
    },
    {
        name: "job_applications",
        table: schema.jobApplications,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            jobId: r.job_id,
            jobTitle: r.job_title,
            fullName: r.full_name,
            email: r.email,
            cvPath: r.cv_path,
            gdprConsent: r.gdpr_consent,
            createdAt: date(r.created_at) ?? new Date(),
        }),
    },
    {
        name: "auto_generated_blog_posts",
        table: schema.autoGeneratedBlogPosts,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            uid: r.uid,
            title: r.title,
            category: r.category,
            tags: r.tags,
            createdAt: date(r.created_at) ?? new Date(),
        }),
    },
    {
        name: "blog_post_examples",
        table: schema.blogPostExamples,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            content: r.content,
            createdAt: date(r.created_at) ?? new Date(),
        }),
    },
    {
        name: "social_post_examples",
        table: schema.socialPostExamples,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            platform: r.platform,
            content: r.content,
            createdAt: date(r.created_at) ?? new Date(),
        }),
    },
    {
        name: "rate_limit_log",
        table: schema.rateLimitLog,
        orderBy: "id",
        identity: true,
        map: (r) => ({
            id: r.id,
            key: r.key,
            createdAt: date(r.created_at) ?? new Date(),
        }),
    },
];

async function fetchAllRows(baseUrl: string, key: string, spec: TableSpec): Promise<Row[]> {
    const rows: Row[] = [];
    for (let offset = 0; ; offset += PAGE_SIZE) {
        const url = `${baseUrl}/rest/v1/${spec.name}?select=*&order=${spec.orderBy}.asc`;
        const res = await fetch(url, {
            headers: {
                apikey: key,
                Authorization: `Bearer ${key}`,
                Range: `${offset}-${offset + PAGE_SIZE - 1}`,
            },
        });
        if (!res.ok) {
            throw new Error(`${spec.name}: fetch failed (${res.status} ${res.statusText}) — ${await res.text()}`);
        }
        const page = (await res.json()) as Row[];
        rows.push(...page);
        if (page.length < PAGE_SIZE) return rows;
    }
}

async function main() {
    const supabaseUrl = process.env.SUPABASE_URL?.replace(/\/$/, "");
    const supabaseKey = process.env.SUPABASE_SECRET_KEY;
    if (!supabaseUrl || !supabaseKey) {
        console.error("Error: SUPABASE_URL and SUPABASE_SECRET_KEY must be set in .env");
        process.exit(1);
    }

    const { db, pool } = getDb();

    try {
        for (const spec of TABLES) {
            const [{ existing }] = (await db.execute(
                sql`select count(*)::int as existing from ${spec.table}`,
            )).rows as [{ existing: number }];

            if (existing > 0) {
                console.log(`• ${spec.name}: target already has ${existing} row(s) — skipping.`);
                continue;
            }

            const rows = await fetchAllRows(supabaseUrl, supabaseKey, spec);
            if (rows.length === 0) {
                console.log(`• ${spec.name}: 0 rows in Supabase — nothing to copy.`);
                continue;
            }

            for (let i = 0; i < rows.length; i += 500) {
                const chunk = rows.slice(i, i + 500).map(spec.map);
                if (spec.identity) {
                    await db.insert(spec.table).overridingSystemValue().values(chunk);
                } else {
                    await db.insert(spec.table).values(chunk);
                }
            }

            if (spec.identity) {
                await db.execute(sql`
                    select setval(
                        pg_get_serial_sequence(${spec.name}, 'id'),
                        coalesce((select max(id) from ${sql.raw(`"${spec.name}"`)}), 0) + 1,
                        false
                    )
                `);
            }

            console.log(`✓ ${spec.name}: copied ${rows.length} row(s).`);
        }

        console.log("\nDone. Now verify counts, then run: npm run migrate:cvs");
    } finally {
        await pool.end();
    }
}

main().catch((err) => {
    console.error("Unexpected error:", err);
    process.exit(1);
});
